In [63]:
import pandas as pd  
import numpy as np 
import matplotlib.pylab as plt  

from sklearn import preprocessing  

%matplotlib inline  

from sklearn.decomposition import PCA  
#from sklearn.impute import KNNImputer  
from sklearn.model_selection import train_test_split
from pandas.plotting import scatter_matrix  
from sklearn.metrics import mean_absolute_error 
from sklearn.metrics import mean_squared_error   #RMSE
from sklearn.neighbors import KNeighborsClassifier

from sklearn.neighbors import KNeighborsRegressor
from sklearn.cluster import KMeans 
from sklearn.metrics import silhouette_score

from adjustText import adjust_text  

pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [64]:
df=pd.read_csv('ratings.csv')

In [65]:
df.head()

   userId  bookId  rating
0       1       1     4.0
1       1       3     4.0
2       1       6     4.0
3       1      47     5.0
4       1      50     5.0

In [66]:
df.columns = df.columns.str.strip().str.lower().str.replace('[^A-Za-z\s]+','')

In [67]:
for x in ['bookid','rating']:
    print('-'*50)
    print(x)
    print(df[x].value_counts(dropna=False)) 
    print('-'*50)

--------------------------------------------------
bookid
1      224
50     213
47     209
32     190
10     137
34     135
39     120
2      118
6      114
16      99
21      95
95      92
19      92
62      90
25      88
11      79
36      75
48      74
17      73
7       64
70      62
3       59
5       59
44      54
22      48
45      45
31      45
58      44
60      44
52      42
29      42
65      36
24      35
69      34
88      31
18      28
79      28
23      27
14      27
9       26
86      25
46      25
12      24
73      24
66      23
15      23
41      23
76      23
28      21
93      21
4       20
20      20
100     20
81      20
97      19
92      19
63      19
57      18
61      18
8       18
13      17
26      17
89      17
43      16
42      15
87      15
85      15
78      14
72      14
27      14
75      14
71      13
38      13
94      13
30      13
83      13
84      13
96      13
33      12
35      11
74      11
82      11
64      11
91      10
99      10
53      10
49      10
68      10
40       9
54       9
80       9
55       8
56       8
37       8
90       7
98       6
59       5
67       5
77       5
51       3
Name: bookid, dtype: int64
--------------------------------------------------
--------------------------------------------------
rating
4.0    1128
3.0     990
5.0     718
2.0     351
3.5     260
1.0     255
4.5     206
2.5     109
1.5      31
0.5      19
Name: rating, dtype: int64
--------------------------------------------------

In [18]:
y=df['rating']

In [19]:
train_X, valid_X, train_y, valid_y = train_test_split(df, y, test_size=0.4, random_state=101)
print('Training set:', train_X.shape, 'Validation set:', valid_X.shape)

Training set: (2440, 3) Validation set: (1627, 3)

In [9]:
train_y

3405    4.0
981     2.0
3429    1.0
1153    5.0
3202    2.5
       ...
3839    3.5
1096    1.0
3980    4.0
235     4.0
1061    2.0
Name: rating, Length: 2440, dtype: float64

In [21]:
cols = ['userid','bookid']

In [22]:
train_X1 = train_X[cols] 
valid_X1 = valid_X[cols]

In [42]:
#scaling the training dataset
scaler = preprocessing.MinMaxScaler()
scaler.fit(train_X1.iloc[:,:-1])
train_X1_scaled=pd.DataFrame(scaler.transform(train_X1.iloc[:,:-1]), columns=train_X1.columns[:-1])
valid_X1_scaled=pd.DataFrame(scaler.transform(valid_X1.iloc[:,:-1]), columns=valid_X1.columns[:-1])

In [43]:
train_X1_scaled

        userid
0     0.773399
1     0.891626
2     0.085386
3     0.326765
4     0.277504
...        ...
2435  0.384236
2436  0.981938
2437  0.325123
2438  0.369458
2439  0.197044

[2440 rows x 1 columns]

In [44]:
valid_X1_scaled=pd.DataFrame(scaler.transform(valid_X1.iloc[:,:-1]), columns=valid_X1.columns[:-1])

In [45]:
valid_X1_scaled

        userid
0     0.791461
1     0.541872
2     0.037767
3     0.390805
4     0.052545
...        ...
1622  0.981938
1623  0.973727
1624  0.678161
1625  0.050903
1626  0.786535

[1627 rows x 1 columns]

In [60]:
df=df.drop(columns='rating')

KeyError: "['rating'] not found in axis"

In [48]:
df

      userid  bookid
0          1       1
1          1       3
2          1       6
3          1      47
4          1      50
...      ...     ...
4062     610      32
4063     610      47
4064     610      50
4065     610      70
4066     610      95

[4067 rows x 2 columns]

In [49]:
df.reset_index(drop=True, inplace=True)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4067 entries, 0 to 4066
Data columns (total 2 columns):
userid    4067 non-null int64
bookid    4067 non-null int64
dtypes: int64(2)
memory usage: 63.7 KB

In [32]:
df_Test = df[cols]

In [33]:
df_Test_scaled=pd.DataFrame(scaler.transform(df_Test.iloc[:,:-1]), columns=df_Test.columns[:-1])

In [29]:
# Train a Classifier for different values of k using train_X1_scaled
results = []
for k in range(1,6):
        knn = KNeighborsClassifier(n_neighbors=k,n_jobs=1).fit(train_X1_scaled,train_y)
        results.append({
            'k': k,
            'MAE': mean_absolute_error(valid_y, knn.predict(valid_X1_scaled))
    })

# Convert results to a pandas data frame
results = pd.DataFrame(results)
results.sort_values(by='MAE')
results.index=results.k
results=results.drop('k',axis=1)
results.plot()

ValueError: Unknown label type: 'continuous'

In [54]:
# Train a Classifier for different values of k using train_X1_scaled
results = []
knn.fit(train_X1_scaled,train_y)
for k in range(1,6):
        knn = KNeighborsClassifier(n_neighbors=k,n_jobs=1)
        results.append({
            'k': k,
            'MAE': mean_absolute_error(valid_y, knn.predict(valid_X1_scaled))
    })

# Convert results to a pandas data frame
results = pd.DataFrame(results)
results.sort_values(by='MAE')
results.index=results.k
results=results.drop('k',axis=1)
results.plot()

ValueError: Unknown label type: 'continuous'

In [28]:
# Train a classifier for different values of k and metric list train_X1_scaled(made from df_starsNotnull)
metric_list=['euclidean','manhattan','chebyshev','minkowski',]
results = []
for k in range(1,6):
    for m in metric_list:
        knn = KNeighborsClassifier(n_neighbors=k,metric=m,n_jobs=-1).fit(train_X1_scaled, train_y)
        results.append({
            'k_distance': str(k)+" "+str(m),
            'MAE': mean_absolute_error(valid_y, knn.predict(valid_X1_scaled))
    })

# Convert results to a pandas data frame
results = pd.DataFrame(results)
results.sort_values(by='MAE')
#results.index=results.k_distance
#results=results.drop('k_distance',axis=1)
#results.plot()

ValueError: Unknown label type: 'continuous'

In [55]:
# Train a Classifier for different values of k using train_X1_scaled
results = []
knn.fit(train_X1_scaled,train_y)
for k in range(1,6):
        knn = KNeighborsClassifier(n_neighbors=k,n_jobs=1)
        results.append({
            'k': k,
            'MAE': mean_absolute_error(valid_y, knn.predict(valid_X1_scaled))
    })

# Convert results to a pandas data frame
results = pd.DataFrame(results)
results.sort_values(by='MAE')
results.index=results.k
results=results.drop('k',axis=1)
results.plot()

ValueError: Unknown label type: 'continuous'

In [59]:
train_X1_scaled.head(100)

      userid
0   0.773399
1   0.891626
2   0.085386
3   0.326765
4   0.277504
5   0.410509
6   0.630542
7   0.116585
8   0.916256
9   0.622332
10  0.154351
11  0.167488
12  0.448276
13  0.008210
14  0.678161
15  0.180624
16  0.047619
17  0.055829
18  0.441708
19  0.866995
20  0.425287
21  0.622332
22  0.244663
23  0.724138
24  0.807882
25  0.486043
26  0.696223
27  0.359606
28  0.297209
29  0.530378
30  0.990148
31  0.228243
32  0.400657
33  0.886700
34  0.776683
35  0.367816
36  0.177340
37  0.395731
38  0.776683
39  0.955665
40  0.988506
41  0.858785
42  0.781609
43  0.950739
44  0.362890
45  0.106732
46  0.996716
47  0.965517
48  0.428571
49  0.528736
50  0.302135
51  0.062397
52  0.014778
53  0.203612
54  0.435140
55  0.957307
56  0.551724
57  0.576355
58  0.981938
59  0.060755
60  0.730706
61  0.589491
62  0.858785
63  0.114943
64  0.029557
65  0.513957
66  0.082102
67  0.926108
68  0.361248
69  0.302135
70  0.536946
71  0.261084
72  0.527094
73  0.277504
74  0.454844
75  0.136289
76  0.469622
77  0.394089
78  0.390805
79  0.105090
80  0.737274
81  0.998358
82  0.261084
83  0.620690
84  0.067323
85  0.798030
86  0.448276
87  0.050903
88  0.980296
89  0.981938
90  0.899836
91  0.789819
92  0.330049
93  0.004926
94  0.960591
95  0.165846
96  0.486043
97  0.036125
98  0.729064
99  0.098522

In [58]:
train_y.head(100)

3099    5.0
3564    5.0
396     4.0
1373    2.5
1145    3.0
1686    4.0
2560    3.0
542     4.5
3623    5.0
2529    4.0
685     4.0
734     4.0
1812    4.0
42      5.0
2726    3.0
780     2.5
210     3.0
263     5.0
1800    2.0
3500    4.0
1719    4.0
2525    4.0
1016    4.0
2906    4.0
3299    5.0
1987    4.0
2802    3.0
1507    5.0
1256    4.5
2187    4.0
4001    4.0
969     4.0
1658    5.0
3550    4.0
3108    3.0
1535    3.0
761     4.0
1644    5.0
3129    4.0
3762    3.0
3975    1.0
3468    3.0
3162    4.5
3739    3.0
1521    3.0
492     3.0
4056    2.0
3800    3.0
1731    3.0
2179    2.5
1275    2.0
280     3.0
89      4.0
881     3.0
1763    5.0
3765    5.0
2264    4.0
2347    5.0
3888    2.5
273     5.0
2924    4.0
2403    2.0
3473    3.0
535     3.0
130     3.0
2120    3.0
381     5.0
3671    5.0
1517    4.5
1277    5.0
2207    5.0
1082    5.0
2166    3.5
1146    3.0
1866    4.0
590     4.0
1920    4.5
1642    4.0
1619    4.0
486     5.0
2961    5.0
4057    3.0
1086    4.0
2512    2.0
308     4.0
3240    5.0
1833    3.0
225     3.0
3865    3.0
3894    3.0
3578    1.0
3198    4.0
1392    2.0
19      3.0
3778    4.0
719     5.0
1991    1.0
168     3.0
2921    4.5
452     4.5
Name: rating, dtype: float64